config/routes.rb
Rails.application.routes.draw do
  resources :rules

  resources :routes do
    collection do
      get 'add_pub_to_list'
    end
  end

  resources :pubs

end

app/models/route.rb
class Route < ActiveRecord::Base

	has_and_belongs_to_many :pubs
	has_many :rules

end

app/controllers/routes_controller.rb
require 'json'

class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]


  # GET /routes
  # GET /routes.json
  def index
    @routes = Route.all
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
    @hash = Gmaps4rails.build_markers(@route.pubs) do |pub, marker|
      marker.lat pub.latitude
      marker.lng pub.longitude
      marker.title pub.name
    end
  end

  # GET /routes/new
  def new
    # Construct a new route
    @route = Route.new
    # Construct and array to save our pubs, this will be added to the route model later
    @pubList = Array.new

    @rule = Rule.new

    # Provide the initial search object
    @search = Pub.search(params[:q])

    # Construct our initial map
    @hash = Gmaps4rails.build_markers(@pubList) do |pub, marker|
      marker.lat pub.latitude
      marker.lng pub.longitude
      marker.title pub.name
    end

  end

  # GET /routes/1/edit
  def edit

    # we then search for our pubs given our search param
    @search = Pub.search(params[:q])
    @pubs = @search.result

    # and add it to our current route
    if(@pubs.size == 1)
      # but only if only 1 pubs is found
      @route.pubs << @pubs[0]
      @route.save
    end

  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)
    @pubList = JSON.parse params[:route][:pubList_id_eq]

    @pubList.each do |pub_id|
      @route.pubs << Pub.find(pub_id)
    end

    respond_to do |format|
      if @route.save
        format.html { redirect_to @route, notice: 'Route was successfully created.' }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: 'Route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_pub_to_list
    # Search for a pub given our param
    @search = Pub.search(params[:q])
    @pubs = @search.result

    respond_to do |format|
      # If our search returns a single pub
      if(@pubs.size == 1)
        # First fetch our pub list
        @pubList = JSON.parse params[:q][:pubList_id_eq]

        # If it's already in the list, then tell the user
        if(@pubList.include?(@pubs[0].id))
          @hash = "That pub's already in your list!"
          # And respond
          format.js
          return
        end

        # Then add the pub to this list
        @pubList << @pubs[0].id

        # Build a merker for the given pub
        @hash = Gmaps4rails.build_markers(@pubs) do |pub, marker|
          marker.lat pub.latitude
          marker.lng pub.longitude
          marker.title pub.name
        end
        @hash = @hash[0]
        # And respond
        format.js

      # If no pubs are found
      elsif(@pubs.size == 0)
        @pubList = JSON.parse params[:q][:pubList_id_eq]
        @hash = "Pub not found, maybe you would like to add this pub to our database?"
        # And respond
        format.js
      else
        @pubList = JSON.parse params[:q][:pubList_id_eq]
        @hash = "We found more then one pub with that name!"
        # And respond
        format.js
      end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:name, :q)
    end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_form.html.erb
<%= form_for(@route) do |f| %>
  <% if @route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% @route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "row">
    <div class = "form-group col-md-3">
      <%= f.text_field :name, class: "form-control", placeholder:"Give your route a name" %>
    </div>
    <div class "form-group col-md-3">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/routes/_map.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<div>
	<div id="map" style='width: 100%; height: 400px;'></div>
</div>

<script>
handler = Gmaps.build('Google');

handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.getMap().setZoom(13);
  handler.map.centerOn({ lat: 53.344103999999990000, lng: -6.267493699999932000})
});
</script>

app/views/routes/_map_search.html.erb
<div class="panel panel-default">
		<div class="panel-heading"><h4>Now, Add some pubs</h4></div>
  		<div class="panel-body">
			<%= search_form_for @search, :url => {:action => "add_pub_to_list"}, :remote => true do |f| %>
				<div class = "row">
					<div class = "form-group col-md-3">
						<%= f.text_field :name_cont, class: "form-control", placeholder: "Search for a pub" %>
					</div>
					<div class = "form-group col-md-3">
						<%= f.submit "Search", class: "btn btn-primary" %>
					</div>
					<%= f.hidden_field :pubList_id_eq, :value =>@pubList %>
				</div>
			<% end %>
			</br>
			<div id = "map_container">
				<%= render partial:'map'%>
			</div>
  		</div>
	</div>

app/views/routes/add_pub_to_list.js.erb
//views/items/from_category.js.erb

if(<%= raw @hash.to_json %> == "Pub not found, maybe you would like to add this pub to our database?") {
	alert(<%= raw @hash.to_json %>);
} 
else if(<%= raw @hash.to_json %> == "We found more then one pub with that name!") {
	alert(<%= raw @hash.to_json %>);
}
else if(<%= raw @hash.to_json %> == "That pub's already in your list!") {
	alert(<%= raw @hash.to_json %>);
}
else{
	handler.addMarker(<%=raw @hash.to_json %>);
	document.getElementById('q_pubList_id_eq').value = ('<%= @pubList.inspect %>');
	document.getElementById('route_pubList_id_eq').value = ('<%= @pubList.inspect %>');
	document.getElementById('pub_count').innerHTML = '<h4>Pub Count: <%= @pubList.size %></h4>';
	if(<%= @pubList.size %> >= 12) {
		document.getElementById('main_submit_button').disabled = false;
	}
}

app/views/routes/add_to_pub_list.js.erb
//views/items/from_category.js.erb
    $("#map_container").html("<%= escape_javascript(render 'map') %>");

app/views/routes/edit.html.erb
<h1>Editing route</h1>

<%= render 'form' %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<h1>Listing routes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.name %></td>
        <td><%= link_to 'Show', route %></td>
        <td><%= link_to 'Edit', edit_route_path(route) %></td>
        <td><%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Route', new_route_path %>

app/views/routes/new.html.erb
<div class = "container">

	<div class="panel panel-default">
		<div class="panel-heading"><h4>First, Add some pubs</h4></div>
  		<div class="panel-body">
			<%= search_form_for @search, :url => {:action => "add_pub_to_list"}, :remote => true do |f| %>
				<div class = "row">
					<div class = "form-group col-md-3">
						<%= f.text_field :name_cont, class: "form-control", placeholder: "Search for a pub" %>
					</div>
					<div class = "form-group col-md-3">
						<%= f.submit "Search", class: "btn btn-primary" %>
					</div>
          <div class = "form col-md-3">
          </div>
          <div class = "form col-md-3">
            <div id = "pub_count"><h4>Pub Count: 0</h4></div>
          </div>
					<%= f.hidden_field :pubList_id_eq, :value =>@pubList %>
				</div>
			<% end %>
			</br>
			<div id = "map_container">
				<%= render partial:'map'%>
			</div>
  		</div>
	</div>

	<!--<div class="panel panel-default">
		<div class="panel-heading"><h4>Finally, make the rules</h4></div>
  		<div class="panel-body">
  			<%= render 'rules/form' %>
  		</div>
  	</div>-->

    <div class="panel panel-default">
    <div class="panel-heading"><h4>Finally, Name your route</h4></div>
      <div class="panel-body">
      <%= form_for(@route) do |outer| %>
          <% if @route.errors.any? %>
            <div id="error_explanation">
                <h2><%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:</h2>
                <ul>
                  <% @route.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                  <% end %>
                </ul>
            </div>
          <% end %>
          <div class = "row">
            <div class = "form-group col-md-3">
                <%= outer.text_field :name, class: "form-control", placeholder:"Give your route a name" %>
            </div>
            <%= outer.hidden_field :pubList_id_eq, :value =>@pubList %>
            <div class = "form-group col-md-2">
                <%= outer.submit class: "btn btn-primary", id: "main_submit_button", :disabled => "true"%>
            </div>
          </div>
      <% end %>
    </div>
  </div>

  	<%= link_to 'Back', routes_path %>
</div>

app/views/routes/new.js.erb
//views/items/from_category.js.erb
    $("#map_container").html("<%= escape_javascript(render 'map') %>");

app/views/routes/show.html.erb
<div class = "container">

	<div class="panel panel-default">
	  	<div class="panel-heading">
	  		<h4><%= @route.name %></h4>
	  	</div>
	  	
	  	<div class="panel-body">
	  		<div class = "row">
	  			<div class = "col-md-6">
	  				content
	  			</div>
	    		<div class = "col-md-6">
	    			<%= render partial:'map'%>
	    		</div>
	    	<div>
			
			<p id="notice"><%= notice %></p>
			<%= link_to 'Edit', edit_route_path(@route) %> |
			<%= link_to 'Back', routes_path %>
		</div>
	</div>
</div>