config/routes.rb
Rails.application.routes.draw do
  resources :rules

  resources :routes do
    collection do
      get 'add_pub_to_list'
    end
  end

  resources :pubs

end

app/models/pub.rb
class Pub < ActiveRecord::Base

	has_and_belongs_to_many :routes

	geocoded_by :full_address
	after_validation :geocode

	attr_accessor :streetName

	def full_address
		unless streetName.nil?
			name + " ," + streetName + ",Dublin,Ireland"
		end

		name + " ,Dublin,Ireland"
	end

end

app/controllers/pubs_controller.rb
class PubsController < ApplicationController
  before_action :set_pub, only: [:show, :edit, :update, :destroy]

  # GET /pubs
  # GET /pubs.json
  def index

    @pubs = Pub.all

    @hash = Gmaps4rails.build_markers(@pubs) do |pub, marker|
      marker.lat pub.latitude
      marker.lng pub.longitude
      marker.title pub.name
    end

    @pub = Pub.new
  end

  # GET /pubs/1
  # GET /pubs/1.json
  def show
  end

  # GET /pubs/new
  def new
    @pub = Pub.new
  end

  # GET /pubs/1/edit
  def edit
  end

  # POST /pubs
  # POST /pubs.json
  def create
    @pub = Pub.new(pub_params)

    respond_to do |format|
      if @pub.save
        format.html { redirect_to @pub, notice: 'Pub was successfully created.' }
        format.json { render :show, status: :created, location: @pub }
      else
        format.html { render :new }
        format.json { render json: @pub.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pubs/1
  # PATCH/PUT /pubs/1.json
  def update
    respond_to do |format|
      if @pub.update(pub_params)
        format.html { redirect_to new_pub_path, notice: 'Pub was successfully updated.' }
        format.json { render :show, status: :ok, location: @pub }
      else
        format.html { render :edit }
        format.json { render json: @pub.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pubs/1
  # DELETE /pubs/1.json
  def destroy
    @pub.destroy
    respond_to do |format|
      format.html { redirect_to pubs_url, notice: 'Pub was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def reload_map
    render :partial => "pubs/_map"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pub
      @pub = Pub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pub_params
      params.require(:pub).permit(:name, :streetName, :latitude, :longitude)
    end
end

app/helpers/pubs_helper.rb
module PubsHelper
end

app/views/pubs/_form.html.erb
</br>
<%= form_for(@pub) do |f| %>
  <% if @pub.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pub.errors.count, "error") %> prohibited this pub from being saved:</h2>

      <ul>
      <% @pub.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <div class = "row">
      <div class = "col-md-6"></div>
      <div class = "col-md-2"><%= f.text_field :name, class: "form-control", placeholder: "Add New Pub"  %></div>
      <div class = "col-md-2"><%= f.text_field :streetName, class: "form-control", placeholder: "StreetName"  %></div>
      <div class = "col-md-2"><%= f.submit class: "btn btn-success btn-block pull-right"  %></div>
    </div>
    </div>
<% end %>

app/views/pubs/_map.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<div>
	<div id="map" style='width: 100%; height: 650px;'></div>
</div>

<script>
handler = Gmaps.build('Google');

handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();;
});
</script>

app/views/pubs/edit.html.erb
<h1>Editing pub</h1>

<%= render 'form' %>

<%= link_to 'Show', @pub %> |
<%= link_to 'Back', pubs_path %>

app/views/pubs/index.html.erb
</br>

<div class="container">

<div class="panel panel-default">
  <div class="panel-body">

  <div class="dynamic"><%= render 'map'%></div>


<div class="row"></div>

  <%= render 'form'%>

</div>
</div>

</div>

<%= link_to 'New Pub', new_pub_path %>

app/views/pubs/new.html.erb
<h1>New pub</h1>

<%= render 'form' %>

<%= link_to 'Back', pubs_path %>

app/views/pubs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pub.name %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @pub.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @pub.longitude %>
</p>

<%= link_to 'Edit', edit_pub_path(@pub) %> |
<%= link_to 'Back', pubs_path %>